# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'


target 'kirito' do
  
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for kirito
    pod 'Firebase/Core', '~> 5.15.0'
    pod 'Firebase/Messaging', '~> 5.15.0'
    pod 'Firebase/Auth', '~> 5.15.0'
  # target 'kirito-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  target 'kiritoTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Firebase/Core', '~> 5.15.0'
    pod 'Firebase/Messaging', '~> 5.15.0'
    pod 'Firebase/Auth', '~> 5.15.0'
  end

end

target 'kirito-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for kirito-tvOS

  target 'kirito-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
